---

- name: Install NGINX
  apt: name=nginx update_cache=yes state=latest

- name: Start NGINX
  become: yes
  service: name=nginx state=started

- name: Copy NGINX configuration
  template: src=test-example.conf dest=/path/to/nginx/thing.conf
  notify: restart nginx
