---
- name: Fetch GPG key
  become: yes
  command: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927
  changed_when: false

- name: Add MongoDB repository
  become: yes
  shell: echo 'deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse' | sudo tee /etc/apt/sources.list.d/mongodb-org-3.2.list
  changed_when: false

- name: Install MongoDB
  become: yes
  apt:
    name: mongodb-org
    update_cache: yes
    cache_valid_time: 3600
    state: latest

- name: Run mongod daemon
  become: yes
  service:
    name: mongod
    state: started

# This module is just a sample for now
# - name: Apply mongod configuration file
#   template:
      # src: mongod.conf.j2
      # dest: /what/ever/path
#   notify: restart mongod
