---

- name: Check which Node.js apps are running
  command: sudo forever list
  become: false
  register: forever_list
  changed_when: false

- name: Start Node.js app
  # Using sudo in command as a workaround for the sudo/su/root issue with starting an app in Forever
  command: sudo forever start {{ app_server_path }}
  become: false
  when: "forever_list.stdout.find('{{ app_server_path }}') == -1"
