---

- name: Create user home directory if necessary
  file: path={{ project_path }} state=directory

- name: Create group
  group: name={{ project_group }} state=present

- name: Create user
  user: name={{ project_user }} group={{ project_group }} home={{ project_path }}
