---

- name: Install basic apt packages
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
    - git
    - build-essential
    - curl
    - htop
    - nodejs # This is less than ideal (outdated) and isn't installing npm on trusty64
