---
- hosts: all
  become: true

  tasks:
    - name: Update apt cache
      apt: update_cache=yes

    - name: Install apt packages
      apt: name={{ item }} state=latest
      with_items:
        - git
        - build-essential

    - name: install node.js

    - name: install mongodb

    - name: install express

    - name: install bower

    - name: install forever
