---
- hosts: all
  become: true
  become_method: sudo
  remote_user: vagrant

  tasks:
    - name: Update apt cache
      apt: update_cache=yes

    - name: Install apt packages
      apt: name={{ item }} state=installed
      with_items:
        - git
        - build-essential
        - curl
        - htop
        - nodejs
