---
- hosts: all
  user: vagrant

  tasks:
    - name: Update apt cache
      apt: update_cache=yes

    - name: Install Git
      apt: name=git state=latest

    - name: Install build-essential
      apt: name=build-essential state=latest

    - name: install node.js

    - name: install mongodb

    - name: install express

    - name: install bower

    - name: install forever
