---

- name: Install basic apt packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
    state: latest
  with_items:
    - git
    - build-essential
    - curl
    - htop
